# Generated by Django 3.1.6 on 2021-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
