# Generated by Django 3.1.6 on 2021-02-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0002_song_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='vote_count',
        ),
    ]
