# Generated by Django 3.1.6 on 2021-02-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0003_remove_song_vote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='author',
            new_name='artist',
        ),
    ]
