# Generated by Django 3.1.6 on 2021-02-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0004_auto_20210216_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Great'), (5, '5 - Excellent')])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_rater.song')),
            ],
        ),
    ]
