# Generated by Django 3.1.6 on 2021-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='1992-04-15 00:00'),
            preserve_default=False,
        ),
    ]
